### ISSUE TITLE
Can this work be transfered to the object detection model,such as yolov5?

### ISSUE THREAD

**Issue by zzhujiuxingc** [kakaobrain/miro#12]
Can this work be transfered to the object detection model,such as yolov5?
If can, please give me some ideas, thanks.

**Comment by khanrc** [comment]
Our work is applicable to the fine-tuning scenario using pre-trained models (to approximate an oracle using the pre-trained model). Thus, if your scenario is fine-tuning, you can use our work directly. Note that the pre-trained model should be sufficiently generalizable to unseen domains in this scenario.
