### ISSUE TITLE
All results based on leave-one-out-validation instead of training-domain-validation?

### ISSUE THREAD

**Issue by BierOne** [kakaobrain/miro#13]
Hi, thanks for this outstanding work. I really appreciate this public code.

In your paper, you mentioned both the leave-one-out selection and training-domain-validation selection. However, as suggested by Domainbed paper (page 18), these are two distinct strategies for model selection.

Could you clarify your employed selection strategy? I am quite confused in this regard.

Thank you so much.

**Comment by khanrc** [comment]
We used `training-domain validation` model selection. `leave-one-out cross-validation` in the paper indicates the evaluation scheme, not the model selection. We agree that this is easy to confuse, and honestly speaking, I think it would have been better if DomainBed had used a different term (the term `leave-one-out cross-validation` have exist before DomainBed).

**Comment by BierOne** [comment]
Got it. Thanks!
