### ISSUE TITLE
results for each domain

### ISSUE THREAD

**Issue by zhangyl660** [kakaobrain/miro#17]
Thanks for your impressive work. Could you provide your detailed results of MIRO+SWAD (Using RegNetY-16GF backbone with SWAG pre-training) for each domain on the 5 datasets? Thank you very much.

**Comment by khanrc** [comment]
<img width="942" alt="image" src="https://github.com/kakaobrain/miro/assets/3657248/75f457f6-90e8-442d-a9bd-43cd89a97b65">

Hope this helps.

**Comment by zhangyl660** [comment]
Thanks again!

**Comment by judgingalready** [comment]
Thanks for the nice work! 

Sorry to bother you again. Could you please provide the detailed results of **MIRO (Using VIT-B pre-trained by CLIP)** for **each domain** on all the datasets? 

Thank you very much.
