### ISSUE TITLE
results for each domain when using VIT-B pre-trained by CLIP

### ISSUE THREAD

**Issue by judgingalready** [kakaobrain/miro#19]
Thanks for the great work!

Sorry to bother you again. Could you please provide the detailed results of **ERM** and **MIRO** **(Using VIT-B pre-trained by CLIP, Table 2)** for each domain on five datasets? It will help me a lot.

Thank you very much again.

**Comment by khanrc** [comment]
# ERM (CLIP-ViT)

|     | iid_avg   | iid_art_painting   | iid_cartoon   | iid_photo   | iid_sketch   |
|:----|:----------|:-------------------|:--------------|:------------|:-------------|
| 0   | 83.01%    | 88.71%             | 85.23%        | 94.24%      | 63.87%       |
| 1   | 82.81%    | 77.55%             | 86.30%        | 90.94%      | 76.43%       |
| 2   | 84.37%    | 75.35%             | 87.74%        | 94.99%      | 79.42%       |
| avg | 83.40%    | 80.54%             | 86.43%        | 93.39%      | 73.24%       |

|     | iid_avg   | iid_Caltech101   | iid_LabelMe   | iid_SUN09   | iid_VOC2007   |
|:----|:----------|:-----------------|:--------------|:------------|:--------------|
| 0   | 74.75%    | 93.90%           | 63.53%        | 73.91%      | 67.64%        |
| 1   | 78.49%    | 95.67%           | 66.16%        | 76.96%      | 75.16%        |
| 2   | 74.52%    | 96.47%           | 67.06%        | 67.75%      | 66.83%        |
| avg | 75.92%    | 95.35%           | 65.58%        | 72.87%      | 69.88%        |

|     | iid_avg   | iid_Art   | iid_Clipart   | iid_Product   | iid_Real World   |
|:----|:----------|:----------|:--------------|:--------------|:-----------------|
| 0   | 67.42%    | 62.05%    | 56.96%        | 74.49%        | 76.19%           |
| 1   | 66.02%    | 58.86%    | 56.67%        | 75.06%        | 73.49%           |
| 2   | 65.61%    | 56.54%    | 54.55%        | 74.80%        | 76.53%           |
| avg | 66.35%    | 59.15%    | 56.06%        | 74.78%        | 75.41%           |

|     | iid_avg   | iid_location_100   | iid_location_38   | iid_location_43   | iid_location_46   |
|:----|:----------|:-------------------|:------------------|:------------------|:------------------|
| 0   | 36.77%    | 38.18%             | 32.89%            | 40.71%            | 35.31%            |
| 1   | 34.88%    | 38.76%             | 22.99%            | 40.08%            | 37.69%            |
| 2   | 34.18%    | 37.36%             | 24.19%            | 44.99%            | 30.19%            |
| avg | 35.28%    | 38.10%             | 26.69%            | 41.93%            | 34.40%            |

|     | iid_avg   | iid_clipart   | iid_infograph   | iid_painting   | iid_quickdraw   | iid_real   | iid_sketch   |
|:----|:----------|:--------------|:----------------|:---------------|:----------------|:-----------|:-------------|
| 0   | 45.28%    | 67.88%        | 23.30%          | 52.32%         | 18.45%          | 57.60%     | 52.12%       |
| 1   | 43.21%    | 68.10%        | 21.45%          | 42.62%         | 19.80%          | 56.01%     | 51.26%       |
| 2   | 44.83%    | 67.98%        | 22.78%          | 44.64%         | 17.16%          | 62.34%     | 54.07%       |
| avg | 44.44%    | 67.99%        | 22.51%          | 46.53%         | 18.47%          | 58.65%     | 52.49%       |

**Comment by khanrc** [comment]
# MIRO (CLIP-ViT)

|     | iid_avg   | iid_art_painting   | iid_cartoon   | iid_photo   | iid_sketch   |
|:----|:----------|:-------------------|:--------------|:------------|:-------------|
| 0   | 96.64%    | 97.01%             | 97.01%        | 99.33%      | 93.19%       |
| 1   | 94.11%    | 95.30%             | 96.59%        | 99.85%      | 84.70%       |
| 2   | 96.15%    | 94.51%             | 96.11%        | 99.85%      | 94.15%       |
| avg | 95.63%    | 95.61%             | 96.57%        | 99.68%      | 90.68%       |

|     | iid_avg   | iid_Caltech101   | iid_LabelMe   | iid_SUN09   | iid_VOC2007   |
|:----|:----------|:-----------------|:--------------|:------------|:--------------|
| 0   | 82.50%    | 99.65%           | 67.91%        | 81.65%      | 80.78%        |
| 1   | 82.58%    | 97.53%           | 68.71%        | 82.90%      | 81.19%        |
| 2   | 81.67%    | 99.38%           | 64.66%        | 81.15%      | 81.49%        |
| avg | 82.25%    | 98.85%           | 67.09%        | 81.90%      | 81.16%        |

|     | iid_avg   | iid_Art   | iid_Clipart   | iid_Product   | iid_Real World   |
|:----|:----------|:----------|:--------------|:--------------|:-----------------|
| 0   | 82.37%    | 80.64%    | 71.33%        | 88.57%        | 88.96%           |
| 1   | 82.53%    | 80.64%    | 73.48%        | 87.92%        | 88.07%           |
| 2   | 82.63%    | 81.10%    | 71.76%        | 89.25%        | 88.41%           |
| avg | 82.51%    | 80.79%    | 72.19%        | 88.58%        | 88.48%           |

|     | iid_avg   | iid_location_100   | iid_location_38   | iid_location_43   | iid_location_46   |
|:----|:----------|:-------------------|:------------------|:------------------|:------------------|
| 0   | 53.70%    | 64.09%             | 47.09%            | 58.69%            | 44.93%            |
| 1   | 55.12%    | 66.46%             | 44.97%            | 63.98%            | 45.06%            |
| 2   | 54.11%    | 64.36%             | 47.93%            | 59.57%            | 44.57%            |
| avg | 54.31%    | 64.97%             | 46.66%            | 60.75%            | 44.86%            |

|     | iid_avg   | iid_clipart   | iid_infograph   | iid_painting   | iid_quickdraw   | iid_real   | iid_sketch   |
|:----|:----------|:--------------|:----------------|:---------------|:----------------|:-----------|:-------------|
| 0   | 53.47%    | 74.74%        | 37.67%          | 59.06%         | 17.22%          | 72.41%     | 59.72%       |
| 1   | 54.35%    | 75.20%        | 36.76%          | 59.79%         | 20.45%          | 72.23%     | 61.68%       |
| 2   | 54.13%    | 74.81%        | 36.79%          | 60.62%         | 18.55%          | 71.82%     | 62.18%       |
| avg | 53.98%    | 74.92%        | 37.07%          | 59.82%         | 18.74%          | 72.15%     | 61.20%       |

**Comment by judgingalready** [comment]
Thank you very, very much for writing so many replies. Wishing you a happy life and a smooth work.
