### ISSUE TITLE
About the TerraInc dataset

### ISSUE THREAD

**Issue by yuu-Wang** [kakaobrain/miro#20]
Hello, I was wondering where you found the TerraInc dataset from, as it seems that there is no such dataset with classification available on the internet at the moment. I would really appreciate it if you could let me know, and I am looking forward to your reply. Thank you.

**Comment by khanrc** [comment]
It is provided by [DomainBed](https://github.com/facebookresearch/DomainBed). Here is the reference: https://arxiv.org/abs/1807.04975
