### ISSUE TITLE
The results of ERM on OfficeHome

### ISSUE THREAD

**Issue by Wang-pengfei** [kakaobrain/miro#3]

**Comment by Wang-pengfei** [comment]
Hi, thanks for your nice work and code!  I found ERM's results on officehome to be much lower than those reported in your paper.
Is there anything to watch out for?

![71748c280f6ffce3217273e8230922a](https://user-images.githubusercontent.com/42035033/169485920-0e04570c-cf4a-43f1-952b-adfa5c2a6973.png)

**Comment by khanrc** [comment]
Make sure you set the HPs correctly.

If you do not know the correct HPs, see https://github.com/khanrc/swad/issues/3#issuecomment-998474029.

**Comment by Wang-pengfei** [comment]
> Make sure you set the HPs correctly.
> 
> If you do not know the correct HPs, see [khanrc/swad#3 (comment)](https://github.com/khanrc/swad/issues/3#issuecomment-998474029).

**Comment by Wang-pengfei** [comment]
Thanks for your reply. We will try this searched HPs again.
