### ISSUE TITLE
Batch size used for CLIP-ViT training

### ISSUE THREAD

**Issue by korts-lew** [kakaobrain/miro#4]
Hello, I make this issue to ask the batch size used for CLIP-ViT experiments in the paper.

As far as I know, you mentioned that the paper used batch size=16 for SWAG due to resource.

Since ViT is also big as RegNet, I think you could use smaller batch size than 32 for the ViT too.

Therefore, I wank to know what batch size is used for the experiments using ViT to reproduce your works exactly. 

Thanks for your great work!

**Comment by khanrc** [comment]
Thank you for your interest in our work.

We used the batch size of 32 for CLIP-ViT, except for DomainNet in which we used the batch size of 24.

**Comment by korts-lew** [comment]
Thank you for your kind reply! 😄
