### ISSUE TITLE
result for each domain

### ISSUE THREAD

**Issue by gkyustc** [kakaobrain/miro#5]
Thanks for your impressive work. Could you provide your results for each domain on the 5 datasets? Thank you very much.

**Comment by khanrc** [comment]
MIRO results for each domain (ResNet-50 and w/o SWAD):

| Domain index | 1 | 2 | 3 | 4 | 5 | 6 | avg |
| - | - | - | - | - | - | - | - |
| PACS | 87.4 | 78.3 | 97.2 | 78.7 | | | 85.4 |
| VLCS | 98.3 | 64.7 | 75.3 | 77.8 | | | 79.0 |
| OfficeHome | 67.5 | 54.6 | 78.0 | 81.6 | | | 70.5 |
| TerraInc | 61.1 | 43.9 | 56.9 | 39.6 | | | 50.4 |
| DomainNet | 63.4 | 21.5 | 50.4 | 12.2 | 65.4 | 52.5 | 44.3 |

For each dataset, domains are sorted in alphabetical order:

```
PACS: art_painting, cartoon, photo, sketch
VLCS: Caltech101, LabelMe, SUN09, VOC2007
OfficeHome: Art, Clipart, Product, Real World
TerraInc: location_100, location_38, location_43, location_46
DomainNet: clipart, infograph, painting, quickdraw, real, sketch
```

**Comment by gkyustc** [comment]
Thank you very much

**Comment by zhangyl660** [comment]
What about results of MIRO+SWAD (Using RegNetY-16GF backbone with SWAG pre-training) for each domain? Thank you very much
