### ISSUE TITLE
Questions about the numbers of TerraIncognita DataSet

### ISSUE THREAD

**Issue by judgingalready** [kakaobrain/miro#9]
Thanks for the nice work! 

I am confused about the numbers of TerraIncognita DataSet. I use the link in download.py, and get 24330 images. But in your paper it's 24788, the same as SWAD and DomainBed. I find similar issue in (https://github.com/facebookresearch/DomainBed/issues/58#issuecomment-1000695053) that noone replys. So I would like to know which version you use(24788 or 24330) and whether it matters.

Thank you again.

**Comment by khanrc** [comment]
Thank you for letting us know the issue. 

We use the dataset of 24788 version. I think it won't be a serious problem, but using the 24788 version of dataset is better if you can get it. Hope this helps, here are the dataset sizes for each domain we used: location_100 (#4879), location_38 (#9767), location_43 (#4020), location_46 (#6122).

**Comment by judgingalready** [comment]
Thanks for your kind reply ! 

But I try my best and cannot find old version. So could you please send this version to my mail(judgingalready@gmail.com) or upload google cloud when it is convenient for you? It will help me a lot.

I know the dataset is big and it's troublesome, and I will close this issue first.

Sorry to bother you again.

**Comment by khanrc** [comment]
Sorry, I looked it up but we don't have the old dataset either. Maybe DomainBed maintainers can help.

**Comment by judgingalready** [comment]
Thanks for your quick reply! It doesn't matter.

**Comment by ipenguin333** [comment]
找见数据集了吗【玫瑰】
